version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employee_db
      MYSQL_USER: bssuser
      MYSQL_PASSWORD: bssuser@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi_app:
    build: .
    container_name: fastapi_container
    environment:
      MYSQL_USER: bssuser
      MYSQL_PASSWORD: bssuser@123
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: employee_db
    ports:
      - "8090:8090"
    depends_on:
      - mysql

volumes:
  mysql_data:
